-- Eliminación en orden inverso a la creación para respetar FKs
DROP TABLE IF EXISTS milla_pago CASCADE;
DROP TABLE IF EXISTS efectivo CASCADE;
DROP TABLE IF EXISTS zelle CASCADE;
DROP TABLE IF EXISTS criptomoneda CASCADE;
DROP TABLE IF EXISTS pago_movil_interbancario CASCADE;
DROP TABLE IF EXISTS transferencia_bancaria CASCADE;
DROP TABLE IF EXISTS deposito_bancario CASCADE;
DROP TABLE IF EXISTS cheque CASCADE;
DROP TABLE IF EXISTS tarjeta_debito CASCADE;
DROP TABLE IF EXISTS tarjeta_credito CASCADE;
DROP TABLE IF EXISTS metodo_pago CASCADE;

DROP TABLE IF EXISTS reembolso CASCADE;
DROP TABLE IF EXISTS pago CASCADE;
DROP TABLE IF EXISTS tasa_de_cambio CASCADE;

DROP TABLE IF EXISTS reserva_restaurante CASCADE;
DROP TABLE IF EXISTS reserva_de_habitacion CASCADE;
DROP TABLE IF EXISTS pue_tras CASCADE;
DROP TABLE IF EXISTS resena CASCADE;
DROP TABLE IF EXISTS reclamo CASCADE;
DROP TABLE IF EXISTS res_est CASCADE;
DROP TABLE IF EXISTS detalle_reserva CASCADE;

DROP TABLE IF EXISTS cuo_est CASCADE;
DROP TABLE IF EXISTS cuota CASCADE;
DROP TABLE IF EXISTS plan_financiamiento CASCADE;
DROP TABLE IF EXISTS compensacion CASCADE;
DROP TABLE IF EXISTS compra CASCADE;
DROP TABLE IF EXISTS estado CASCADE;

DROP TABLE IF EXISTS auditoria CASCADE;
DROP TABLE IF EXISTS recurso CASCADE;
DROP TABLE IF EXISTS accion CASCADE;
DROP TABLE IF EXISTS preferencia CASCADE;
DROP TABLE IF EXISTS categoria CASCADE;
DROP TABLE IF EXISTS lista_deseos CASCADE;
DROP TABLE IF EXISTS milla CASCADE;

DROP TABLE IF EXISTS puesto CASCADE;
DROP TABLE IF EXISTS traslado CASCADE;
DROP TABLE IF EXISTS ruta CASCADE;
DROP TABLE IF EXISTS terminal CASCADE;

DROP TABLE IF EXISTS reg_paq_paq CASCADE;
DROP TABLE IF EXISTS regla_paquete CASCADE;
DROP TABLE IF EXISTS paq_ser CASCADE;
DROP TABLE IF EXISTS paq_tras CASCADE;
DROP TABLE IF EXISTS paq_prom CASCADE;
DROP TABLE IF EXISTS paquete_turistico CASCADE;
DROP TABLE IF EXISTS ser_prom CASCADE;
DROP TABLE IF EXISTS tras_prom CASCADE;
DROP TABLE IF EXISTS servicio CASCADE;
DROP TABLE IF EXISTS promocion CASCADE;

DROP TABLE IF EXISTS habitacion CASCADE;
DROP TABLE IF EXISTS plato CASCADE;
DROP TABLE IF EXISTS restaurante CASCADE;
DROP TABLE IF EXISTS hotel CASCADE;
DROP TABLE IF EXISTS telefono CASCADE;

DROP TABLE IF EXISTS medio_transporte CASCADE;
DROP TABLE IF EXISTS proveedor CASCADE;
DROP TABLE IF EXISTS lugar CASCADE;

DROP TABLE IF EXISTS via_edo CASCADE;
DROP TABLE IF EXISTS estado_civil CASCADE;
DROP TABLE IF EXISTS documento CASCADE;
DROP TABLE IF EXISTS viajero CASCADE;
DROP TABLE IF EXISTS nacionalidad CASCADE;

DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS rol_privilegio CASCADE;
DROP TABLE IF EXISTS privilegio CASCADE;
DROP TABLE IF EXISTS rol CASCADE;


--Agregada para la tabla nueva con el tema de los pagos, no funcionaba bien el sp y por eso las millas no se registraban
DROP TABLE IF EXISTS tipo_metodo_pago CASCADE;